version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgress
    restart: on-failure
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: "postgress"
      POSTGRES_DB: postgress
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5433"
    
  backend:
    image: backend:latest
    hostname: backend
    container_name: backend
    ports:
      - "5009:5009"
    restart: always
    
volumes:
  db-data: