version: "3"
services:
  postgresss:
    image: library/postgres:17
    container_name: postgresss
    restart: on-failure
    environment:
      POSTGRES_USER: postgresss
      POSTGRES_PASSWORD: "postgresss"
      POSTGRES_DB: postgresss
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgresss/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    
  backend:
    image: backend:latest
    hostname: backend
    container_name: backend
    ports:
      - "8070:8070"
    restart: always
    
    
volumes:
  db-data: