name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - develop
    pull_request:
      branches:
        - master
        - develop
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: .Net
        uses: actions/setup-dotnet@v3 
        with: 
          dotnet-version: '9.0.x'
            
      - name: Dependencies
        run: dotnet restore src/Person/Person.sln
        
      - name: Publish
        run: dotnet publish src/Person/Person.Server/Person.Server.csproj -c Release -o PersonPublish
        
      - name: Docker Image
        run: |
          docker build -t backend:latest ./
          docker save backend:latest > backend.tar
          
      - name: Save Image
        uses: actions/upload-artifact@v4
        with:
          name: backend-image
          path: backend.tar
        
  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - uses: actions/checkout@v3
            
      - name: .Net
        uses: actions/setup-dotnet@v3 
        with: 
          dotnet-version: '9.0.x'
                
      - name: Run Unit Tests
        run: dotnet test src/Person/Person.sln
        
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      
      - name: Download Image 
        uses: actions/download-artifact@v4
        with:
          name: backend-image
          
      - name: Copy Image 
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "backend.tar"
          target: "/home/rsoitema/"
          owerwrite: true